[project]
name = "mnemnk-langchain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Akira Ishino", email = "akira@lumilab.jp" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
mnemnk-langchain = "mnemnk_langchain:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
